apiVersion: apps/v1
kind: Deployment
metadata:
  name: knote
spec:
  replicas: 3
  selector:
    matchLabels:
      app: knote
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: knote
    spec:
      containers:
        - name: knote
          image: ldrago/todolist:v8
          resources:
            limits:
              memory: "256Mi"
              cpu: "0.5"
            requests:
              cpu: "0.25"
              memory: "128Mi"
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_HOST
              value: mongo
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
            - name: MINIO_ACCESS_KEY
              value: key
            - name: MINIO_SECRET_KEY
              value: val


