apiVersion: apps/v1
kind: Deployment
metadata:
  name: knote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knote
  template:
    metadata:
      labels:
        app: knote
    spec:
      containers:
        - name: knote
          image: ldrago/todolist:v5
          resources:
            limits:
              memory: "256Mi"
              cpu: "1"
            requests:
              cpu: "0.5"
              memory: "128Mi"
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_HOST
              value: mongo
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
            - name: MINIO_ACCESS_KEY
              value: key
            - name: MINIO_SECRET_KEY
              value: val
    

