apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  resources:
    requests:
      storage: 256Mi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mvertes/alpine-mongo:latest
          volumeMounts:
            - name: storage
              mountPath: /data/db
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              cpu: "0.5"
              memory: "256Mi"
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mongo-pvc
              
    


  
  

