version: '3'
services:
  flask:
    build:
      context: app
      dockerfile: DockerFile
    container_name: flask
    image: digitalocean.com/flask-python:3.6
    environment:
      APP_PORT: 5000
      MONGODB_DATABASE: flaskdb
      MONGODB_HOSTNAME: mongodb
    volumes:
      - appdata:/var/www
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: flaskdb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db